# Generated by Django 2.2.13 on 2020-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_product_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, default='media/noimage.jpg', null=True, upload_to='media/'),
        ),
    ]
