# Generated by Django 2.2.13 on 2020-09-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20200910_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6),
            preserve_default=False,
        ),
    ]
