# Generated by Django 2.2.13 on 2020-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_auto_20200915_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='thicknes',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
