# Generated by Django 2.2.13 on 2020-11-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_auto_20201109_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
