# Generated by Django 2.2.13 on 2020-11-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='edge',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='papermake',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='friendly_name',
            field=models.CharField(default='NA', max_length=254),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='name',
            field=models.CharField(default='na', max_length=254),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(default='Description', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tel',
            field=models.DecimalField(decimal_places=0, default='1234', max_digits=11),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='thicknes',
            name='friendly_name',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='thicknes',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
